import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const agents = [
  {
    name: "売上データ分析AI",
    description: "CSVの売上データをアップロードするだけで、売上傾向・トップ商品・改善提案を自動でレポートします。",
    category: "Business",
    agentType: "prompt",
    prompt: "あなたはプロの売上分析コンサルタントです。アップロードされた売上データを分析して、以下の形式でレポートを作成してください。\n\n## 売上サマリー\n## 売上トップ商品\n## 改善提案\n## 来月の予測\n\nデータがない項目は推測で補完してください。日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "売上データまたは状況", type: "textarea", placeholder: "売上データや現状を入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "競合分析AI",
    description: "競合他社の情報を入力するだけで、強み・弱み・差別化ポイントを自動分析します。",
    category: "Research",
    agentType: "prompt",
    prompt: "あなたはプロの競合分析コンサルタントです。入力された競合情報をもとに以下の形式で分析してください。\n\n## 競合の強み\n## 競合の弱み\n## 自社の差別化ポイント\n## 推奨アクション\n\n日本語で具体的に回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "競合情報・業種・自社の強み", type: "textarea", placeholder: "競合他社名、業種、自社の強みなどを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "求人票生成AI",
    description: "職種・条件を入力するだけで、応募が集まる求人票を自動生成します。",
    category: "Business",
    agentType: "prompt",
    prompt: "あなたはプロの採用コンサルタントです。入力された情報をもとに、応募者が魅力を感じる求人票を作成してください。\n\n## 仕事内容\n## 求める人物像\n## 給与・待遇\n## 職場環境\n## 応募方法\n\n日本語で具体的かつ魅力的に書いてください。",
    fields: JSON.stringify([{ id: "f1", label: "職種・給与・特徴など", type: "textarea", placeholder: "職種、給与、仕事の特徴などを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "SNS投稿文生成AI",
    description: "伝えたいことを入力するだけで、X・Instagram・Facebook用の投稿文を自動生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはプロのSNSマーケターです。入力された情報をもとに、各SNSに最適化した投稿文を作成してください。\n\n## X（Twitter）用（140文字以内）\n## Instagram用（ハッシュタグ10個含む）\n## Facebook用（詳細版）\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "伝えたいこと・業種・ターゲット", type: "textarea", placeholder: "告知内容、業種、ターゲット層などを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "議事録生成AI",
    description: "会議のメモを貼り付けるだけで、見やすい議事録を自動生成します。",
    category: "Business",
    agentType: "prompt",
    prompt: "あなたはプロの秘書です。入力された会議の内容をもとに、見やすい議事録を作成してください。\n\n## 会議概要\n## 決定事項\n## 議論内容\n## アクションアイテム\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "会議の内容・メモ", type: "textarea", placeholder: "会議で話し合った内容をそのまま貼り付けてください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "事業計画書生成AI",
    description: "ビジネスアイデアを入力するだけで、投資家に提出できる事業計画書の骨子を生成します。",
    category: "Business",
    agentType: "prompt",
    prompt: "あなたはプロの経営コンサルタントです。入力されたビジネス情報をもとに、説得力のある事業計画書を作成してください。\n\n## エグゼクティブサマリー\n## 市場分析\n## ビジネスモデル\n## 収益計画\n## リスクと対策\n\n日本語で具体的に回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "ビジネスアイデア・ターゲット市場", type: "textarea", placeholder: "ビジネスアイデア、ターゲット市場などを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "YouTubeタイトル生成AI",
    description: "動画の内容を入力するだけで、クリック率が上がるタイトルを10案生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはYouTubeのSEOとタイトル最適化の専門家です。入力された動画情報をもとに、クリック率が高いタイトルを10案生成してください。各タイトルに数字・感情ワード・SEOキーワードを含めてください。さらにサムネイルコピーも3案生成してください。日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "動画の内容・ジャンル・ターゲット", type: "textarea", placeholder: "動画の内容、チャンネルジャンル、ターゲット視聴者を入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "物件紹介文生成AI",
    description: "物件情報を入力するだけで、問い合わせが増える不動産紹介文を生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはプロの不動産コピーライターです。入力された物件情報をもとに、問い合わせが増える魅力的な紹介文を作成してください。\n\n## キャッチコピー（20文字以内）\n## 物件の魅力（3つのポイント）\n## 詳細説明（200文字程度）\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "物件情報", type: "textarea", placeholder: "物件の種類、所在地、間取り、価格、アピールポイントを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "顧客対応メール生成AI",
    description: "クレームや問い合わせを入力するだけで、丁寧な返信メールを自動生成します。",
    category: "Business",
    agentType: "prompt",
    prompt: "あなたはプロのカスタマーサポート担当者です。入力された顧客からの問い合わせ・クレーム内容をもとに、丁寧で誠実な返信メールを作成してください。件名と本文を含めて作成してください。過度に謝罪せず、解決策を明示してください。日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "顧客からの内容", type: "textarea", placeholder: "顧客からのクレームや問い合わせ内容を入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "メニュー説明文生成AI",
    description: "料理名と食材を入力するだけで、注文したくなるメニュー説明文を生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはプロのフードライターです。入力された料理情報をもとに、お客様が注文したくなる魅力的なメニュー説明文を作成してください。説明文は2〜3文で簡潔にまとめてください。日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "料理名・食材・ジャンル", type: "textarea", placeholder: "料理名、使用食材、お店のジャンルを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "英語メール翻訳・返信AI",
    description: "英語のメールを貼り付けるだけで、日本語訳と適切な返信文を自動生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはプロの英語翻訳者です。入力された英語メールを日本語に翻訳し、適切な返信メールを英語で作成してください。\n\n## 日本語訳\n## 返信メール（英語）\n## 返信メール（日本語）\n\nビジネスシーンに適した丁寧な表現を使ってください。",
    fields: JSON.stringify([{ id: "f1", label: "英語メールの内容", type: "textarea", placeholder: "翻訳・返信したい英語メールを貼り付けてください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "プレスリリース生成AI",
    description: "新商品・サービス情報を入力するだけで、メディア掲載されやすいプレスリリースを生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはプロの広報担当者です。入力された情報をもとに、メディアに掲載されやすいプレスリリースを作成してください。\n\n## タイトル\n## リード文\n## 背景・経緯\n## サービス詳細\n## 会社概要\n## 問い合わせ先\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "商品・サービス情報", type: "textarea", placeholder: "新商品やサービスの詳細、背景、会社名などを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "LP（ランディングページ）コピーAI",
    description: "商品・サービス情報を入力するだけで、CVRが高いLPのコピーを自動生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはプロのコピーライターです。入力された情報をもとに、コンバージョン率が高いランディングページのコピーを作成してください。\n\n## キャッチコピー\n## サブコピー\n## 3つの特徴\n## お客様の声（想定）\n## CTA文言\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "商品・サービス情報・ターゲット", type: "textarea", placeholder: "商品名、特徴、ターゲット顧客、価格などを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "コードレビューAI",
    description: "コードを貼り付けるだけで、バグ・改善点・セキュリティ問題を自動でレビューします。",
    category: "Code",
    agentType: "prompt",
    prompt: "あなたはシニアエンジニアです。入力されたコードをレビューして、以下の観点で指摘してください。\n\n## バグ・エラーの可能性\n## パフォーマンスの改善点\n## セキュリティの問題\n## コードの可読性\n## 改善後のコード例\n\n日本語で具体的に回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "レビューしたいコード", type: "textarea", placeholder: "レビューしたいコードを貼り付けてください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "SQL生成AI",
    description: "やりたいことを日本語で入力するだけで、最適なSQLクエリを自動生成します。",
    category: "Code",
    agentType: "prompt",
    prompt: "あなたはデータベースの専門家です。入力された要件をもとに、最適なSQLクエリを生成してください。\n\n## SQLクエリ\n## 解説\n## 注意点\n\nMySQL・PostgreSQL・SQLiteに対応した汎用的なSQLを生成してください。",
    fields: JSON.stringify([{ id: "f1", label: "やりたいこと・テーブル構造", type: "textarea", placeholder: "例: ユーザーテーブルから30日以内に登録した人を取得したい", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "正規表現生成AI",
    description: "マッチさせたいパターンを日本語で説明するだけで、正規表現を自動生成します。",
    category: "Code",
    agentType: "prompt",
    prompt: "あなたは正規表現の専門家です。入力された要件をもとに、正規表現パターンを生成してください。\n\n## 正規表現\n## 解説\n## 使用例（JavaScript）\n## マッチする例・しない例\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "マッチさせたいパターン", type: "textarea", placeholder: "例: 日本の電話番号にマッチする正規表現を作りたい", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "投資判断サポートAI",
    description: "銘柄・企業情報を入力するだけで、投資判断に役立つ分析レポートを生成します。",
    category: "Finance",
    agentType: "prompt",
    prompt: "あなたはプロのファイナンシャルアナリストです。入力された情報をもとに、投資判断に役立つ分析を提供してください。※これは情報提供であり、投資助言ではありません。\n\n## 企業概要\n## 強み・弱み\n## 成長性の評価\n## リスク要因\n## 総合評価\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "銘柄名・企業情報", type: "textarea", placeholder: "分析したい銘柄名や企業情報を入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "契約書チェックAI",
    description: "契約書の文章を貼り付けるだけで、リスクのある条項を自動でチェックします。",
    category: "Legal",
    agentType: "prompt",
    prompt: "あなたはプロの法務担当者です。入力された契約書の内容をチェックして、リスクのある条項を指摘してください。※これは情報提供であり、法的助言ではありません。\n\n## リスクのある条項\n## 修正提案\n## 追加すべき条項\n## 総合評価\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "契約書の内容", type: "textarea", placeholder: "チェックしたい契約書の文章を貼り付けてください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "医療症状チェックAI",
    description: "症状を入力するだけで、考えられる原因と受診すべき診療科を案内します。",
    category: "Medical",
    agentType: "prompt",
    prompt: "あなたは医療情報の専門家です。入力された症状をもとに、考えられる原因と対処法を案内してください。※これは医療診断ではありません。必ず医師に相談してください。\n\n## 考えられる原因\n## 緊急度の評価\n## 受診すべき診療科\n## 自宅でできる対処法\n\n日本語で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "症状・いつから・その他の情報", type: "textarea", placeholder: "症状、いつから始まったか、その他気になる点を入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "ブログ記事生成AI",
    description: "テーマを入力するだけで、SEOに強いブログ記事を自動生成します。",
    category: "Writing",
    agentType: "prompt",
    prompt: "あなたはSEOとコンテンツマーケティングの専門家です。入力されたテーマをもとに、検索上位を狙えるブログ記事を作成してください。\n\n## タイトル（SEOキーワード含む）\n## 導入文\n## 本文（見出しh2・h3含む）\n## まとめ\n## メタディスクリプション\n\n日本語で2000文字程度で回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "記事テーマ・ターゲット読者・キーワード", type: "textarea", placeholder: "例: 副業初心者向けのブログ収益化について書きたい", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
  {
    name: "面接対策AI",
    description: "志望企業・職種を入力するだけで、想定質問と回答例を自動生成します。",
    category: "Business",
    agentType: "prompt",
    prompt: "あなたはプロのキャリアコンサルタントです。入力された情報をもとに、面接対策をサポートしてください。\n\n## 想定質問10個\n## 各質問の回答例\n## アピールすべきポイント\n## 注意すべき点\n\n日本語で具体的に回答してください。",
    fields: JSON.stringify([{ id: "f1", label: "志望企業・職種・経歴", type: "textarea", placeholder: "志望企業名、職種、これまでの経歴や強みを入力してください", options: "", required: true }]),
    authorName: "Lattice", price: 0,
  },
];

async function main() {
  console.log("Seeding agents...");
  for (const agent of agents) {
    await prisma.agent.create({ data: agent });
    console.log(`Created: ${agent.name}`);
  }
  console.log("Done!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());